version: '3.8'

services:
  #PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: fashop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fashop_network

  #Redis
  redis:
    image: redis:7-alpine
    container_name: fashop_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fashop_network

  #Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fashop_backend
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - backend_static:/app/src/static
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - fashop_network

  #Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fashop_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fashop_network

networks:
  fashop_network:
    driver: bridge

volumes:
  postgres_data:
  backend_static: