"""Add contact info columns to orders

Revision ID: 8596dc0e1549
Revises: d5dfd189392a
Create Date: 2026-07-16 00:24:46.867876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8596dc0e1549'
down_revision: Union[str, Sequence[str], None] = 'd5dfd189392a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('address', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
